hr-rfp55-fec7-zuko/project-catwalk

.eslintrc.js, client/dist/index.html, package-lock.json, server/index.js
Server/index.js set up to port 3000, index.html updated. 
@vannguyen-vn @thecaitlinkinney @irislavie  Can I get a code review? https://trello.com/c/sCxJtNqB
=> Setup server

client/src/Components/ProductOverview/ProductOverview.jsx, client/src/index.jsx
Created src/Components and src/Components/ProductOverview folders, ProductOverview.jsx file, imported file to index.jsx and rendered in app. https://trello.com/c/d6hLToPe
Can someone review my code? @irislavie @vannguyen-vn @thecaitlinkinney
=> Init product widget

client/dist/index.html
@thecaitlinkinney , @isabell-lee , @irislavie @vannguyen-vn : Can you review code for me!
=> Testing for pull request

package-lock.json, package.json
https://trello.com/c/WLVOj9IO 
Please review @vannguyen-vn @thecaitlinkinney @irislavie
=> npm installed react testing library

server/index.js, server/poRoutes.js, server/productRoutes.js
-Make a poRoutes.js file within server
-create routes using express router, for handling server requests that will make axios requests to atelier API
-require file to server/index.js
Ticket: https://trello.com/c/aad4M2ZO
@vannguyen-vn @thecaitlinkinney @irislavie Please review. This is currently not tested yet, just a skeleton structure that may need fixing or refactoring later.
=> Product overview routes

client/src/Components/QuestionAnswer/AnswerEntryList.jsx, client/src/Components/QuestionAnswer/QuestionAnswer.jsx, client/src/Components/QuestionAnswer/QuestionAnswerEntryList.jsx, client/src/Components/QuestionAnswer/QuestionEntryList.jsx, client/src/index.jsx, server/index.js, server/qaRoutes.js, tests/qa.test.js
Tasks Completed:
1.  Add server routes and API request function
2. Add client side rendering on questions
@vannguyen-vn @thecaitlinkinney @isabell-lee Can you please help review? 
https://trello.com/c/whVzMfFf
=> Set up Server and Client side for Question List and Add two testings for Server

client/src/Components/ProductOverview/ProductOverview.jsx, client/src/app.jsx, package-lock.json, package.json
No associated trello ticket, I was just playing around and decided to keep this API for doing client side HTTP requests.
ky (https://github.com/sindresorhus/ky) is a lightweight HTTP client based API that I installed and got working after also installing core-js and runtime-regenerator. It fulfills what my widget needs for GET requests.
`ky.get('http://localhost:3000/products/40344').json()
.then((response) => console.log(response));`
This gets the product information successfully as an object. It's pretty easy to use for GET requests and that's all my widget needs. 
@vannguyen-vn @thecaitlinkinney @irislavie  Can you review?
=> Installed ky and dependencies core-js and regenerator-runtime for ajax requests

client/src/app.jsx
Not associated ticket.
Together with entire team on screen share, added a constructor to App class component and hardcoded in a product_id state that was then passed into the components. 
Please review @thecaitlinkinney @irislavie @vannguyen-vn
=> Hardcord state product_id and passed in as prop to components

babel.config.js, jest.config.js, server/productRoutes.js, tests/po.test.js
https://trello.com/c/0OEtoH4C
Added tests to po.test.js that test the server routes created in server/productRoutes.js.
Added/updated some config files 
Added a route for handling '/' in productRoutes.js
=> server product routes testing

client/src/Components/ProductOverview/ProductOverview.jsx, client/src/Components/RelatedProducts/RelatedProductCard.jsx, client/src/Components/RelatedProducts/RelatedProductsList.jsx, client/src/Components/RelatedProducts/RelatedProductsView.jsx, client/src/app.jsx, tests/relatedpo.test.js
https://trello.com/c/xV9j0Xxj
Please review the code for me!
=> Related Product: get related products from API server

client/dist/style.css, client/src/Components/ProductOverview/POComponents/StyleSelector.jsx, client/src/Components/ProductOverview/ProductOverview.jsx, client/src/app.jsx, server/productRoutes.js, tests/po.test.js
https://trello.com/c/xgtJZA8A https://trello.com/c/SbfKL6WY
- Get the product information based on the id prop passed in and set the state for variables that depend on getting a product id. 
- Get the style information based on the id prop and pass into style selector.
-Style selector displays current style based on the default setting or what the user clicks
-Style selector renders images for each style
-Style selector handles user clicks, and will pass selected style back up to product overview component
Please Review!
=> Product overview handling props and state, began implementing style selector

client/dist/style.css, client/src/Components/ProductOverview/POComponents/AddToCart.jsx, client/src/Components/ProductOverview/POComponents/Price.jsx, client/src/Components/ProductOverview/POComponents/SingleStyle.jsx, client/src/Components/ProductOverview/POComponents/StyleSelector.jsx, client/src/Components/ProductOverview/ProductOverview.jsx, package-lock.json, package.json
https://trello.com/c/hNRdDGbZ
Did from ticket so far:
Product Information
-Large Product Name
-Price changes based on sale information
Style Selector
-Bold "Style >" dynamic style change
-Style images are small and round
Cart
-Size and Quantity on same line,
Product Info
-Slogan with description
-Features, no bullets, same block as slogan
Please review
=> Product Overview styling

client/dist/style.css, client/src/Components/QuestionAnswer/AddAnswerList.jsx, client/src/Components/QuestionAnswer/AnswerCountList.jsx, client/src/Components/QuestionAnswer/AnswerEntryList.jsx, client/src/Components/QuestionAnswer/AnswerReportList.jsx, client/src/Components/QuestionAnswer/QuestionAnswer.jsx, client/src/Components/QuestionAnswer/QuestionCountList.jsx, client/src/Components/QuestionAnswer/QuestionEntryList.jsx, client/src/Components/QuestionAnswer/QuestionReportList.jsx, server/qaRoutes.js
1. Populated Answer List
2. Updated Mark as Helpful and Report functionality for both client and server sides
Trello: https://trello.com/c/whVzMfFf https://trello.com/c/rk5oxmcg
=> QA - update functionality on Question and Answer List

client/dist/style.css, client/src/Components/RatingsAndReviews/AddReviewForm.jsx
@isabell-lee @irislavie @vannguyen-vn 
Pls review!
-Fixes <br> tags
-removes white space in CSS
=> Widget skeleton

client/dist/style.css
@vannguyen-vn @thecaitlinkinney @isabell-lee Please review, one minor minor minor change!
=> commented out line 119 in css file

client/dist/style.css, client/src/Components/RelatedProducts/ComparisonModal.jsx, client/src/Components/RelatedProducts/RelatedProductCard.jsx, client/src/Components/YourOutfitList/YourOutfitCard.jsx, client/src/Components/YourOutfitList/YourOutfitList.jsx
https://trello.com/c/8hcssKJF
Please, review it for me!
=> Related Product: Comparison Modal

client/dist/index.html, client/dist/style.css, client/src/Components/RatingsAndReviews/RatingsAndReviews.jsx, client/src/Components/RatingsAndReviews/helpers/AvgRatingStars.jsx, client/src/app.jsx, package-lock.json, package.json
@isabell-lee @vannguyen-vn @irislavie 
Alright - These updates should work for creating an average star rating component that can be used across modules. 
Trello Ticket: https://trello.com/c/fiaxZZXH 
-CSS: Adds proper styling to create stars
-App: Implements request for meta-data after initial component mount. Calculates average rating and saves in state. Includes notes on how to use star component in comments. 
-avgStarRating: Implements function that creates five star component based on average rating 
-HTML + Package: Installs FontAwesome
Notes: 
-Passing average star rating back up from my module created nesting issues with state and component lifecycle, which is why I implemented the axios request from App.  
-Time permitting, I will revisit to see if I can solve the issue with star …
=> Avg rating stars

client/dist/index.html, client/dist/style.css, client/src/Components/QuestionAnswer/AddAnswerList.jsx, client/src/Components/QuestionAnswer/AddAnswerModal.jsx, client/src/Components/QuestionAnswer/QuestionAnswer.jsx, client/src/Components/QuestionAnswer/QuestionEntryList.jsx
1. Added modal component for Add Answer Form in QA section
2. I confirmed website renders properly with this PR.
Trello: https://trello.com/c/L7eQfEEi
=> Added Modal for Add Answer in QA section

client/dist/style.css, client/src/Components/RatingsAndReviews/RatingBreakdown.jsx, client/src/Components/RatingsAndReviews/RatingsAndReviews.jsx, client/src/Components/RatingsAndReviews/ReviewList.jsx, client/src/Components/RatingsAndReviews/ReviewTile.jsx, client/src/Components/RatingsAndReviews/helpers/RatingBar.jsx, client/src/app.jsx, package-lock.json, package.json, server/rrRoutes.js
@vannguyen-vn @irislavie @isabell-lee 
Hi there - Can you please review this for me? 
Updates should mostly be confined to RatingsAndReviews/RatingsBreakdown.jsx, RatingsAndReviews/helpers/RatingBar.jsx, and CSS.
If there are updates from many other folders coming through, I think this is coming from merging my main to the feature branch. 
Updates to ratings breakdown: 
- Adds CSS to create
- Adds star component 
- Creates rating bars as separate components to avoid console warnings
Trello: https://trello.com/c/KbeVtiYn
=> Ratings breakdown

client/src/Components/ProductOverview/POComponents/AddToCart.jsx, client/src/Components/ProductOverview/POComponents/QuantitySelector.jsx, client/src/Components/ProductOverview/POComponents/SizeSelector.jsx, package-lock.json, server/cartRoutes.js, server/index.js, tests/po.test.js
Trello ticket: https://trello.com/c/jjizywoK
-most recently selected size and quantity is saved in state
-add cart button goes post request to the API cart
More details:
-added server routes for cart API and client request to server got get and post
-added request details: if size not selected, message will pop up and selection will open. quantity state is tracked correctly based on visual selection. adding to cart creates message pop up.
-added key to list children
Please review
=> Cart routes

client/dist/style.css, client/src/Components/ProductOverview/POComponents/AddToCart.jsx
https://trello.com/c/jjizywoK 
Made the select size menu not push down the add to cart button when you click add to cart and the size hasn't been selected yet.
Please review.
=> Tinkered with select size dropdown menu

client/dist/index.html, client/dist/style.css, client/src/Components/RatingsAndReviews/AddReviewForm.jsx, client/src/Components/RatingsAndReviews/RatingsAndReviews.jsx, client/src/Components/RatingsAndReviews/ReviewList.jsx, client/src/app.jsx
@isabell-lee @vannguyen-vn @irislavie 
Hi! Can you please review? 
Trello: https://trello.com/c/v3pfHCY0 
Purpose: Creates submit review modal, captures form data in modal state
Updates should mostly live in these files: 
-index.html (add modal)
-RatingsAndReviews/AddReviewForm.jsx
-RatingsAndReviews/RatingsAndReviews.jsx
-RatingsAndReviews/ReviewList.jsx
-CSS
=> Form submit

client/dist/style.css, client/src/Components/ProductOverview/POComponents/ImageGallery.jsx, client/src/Components/ProductOverview/ProductOverview.jsx
https://trello.com/c/8StDPHYj
Worked on the Product Overview Image Gallery Default view
Currently
- Displays full size image on 60% of the screen for default view
- functional buttons to scroll between images
- maintains index when changing styles
- changes photo set when style changes
- hover over the image makes cursor into a magnifying glass
- has an expand view button and click handle function for expanding -- function not implemented. 
Please review.
=> Image gallery default view

client/dist/style.css, client/src/Components/RatingsAndReviews/ProductBreakdown.jsx, client/src/Components/RatingsAndReviews/helpers/ProductBar.jsx, server/rrRoutes.js
@vannguyen-vn @irislavie @isabell-lee 
Smaller pull request! Just looking to consolidate work from this branch since I'm moving more elsewhere. 
Trello ticket: https://trello.com/c/jJzuDar9
Overall, this creates some of the structure for the product breakdown bars, so most updates should be found in css, RatingsAndReviews.jsx and productBreakdown.jsx;
=> Product breakdown

client/dist/style.css, client/src/Components/QuestionAnswer/AddAnswerList.jsx, client/src/Components/QuestionAnswer/AddQuestionList.jsx, client/src/Components/QuestionAnswer/AnswerCountList.jsx, client/src/Components/QuestionAnswer/AnswerEntryList.jsx, client/src/Components/QuestionAnswer/AnswerReportList.jsx, client/src/Components/QuestionAnswer/QuestionAnswer.jsx, client/src/Components/QuestionAnswer/QuestionCountList.jsx, client/src/Components/QuestionAnswer/QuestionEntryList.jsx, client/src/Components/QuestionAnswer/QuestionReportList.jsx, client/src/app.jsx, server/qaRoutes.js
1. Added questions modal and make sure server works and posted
2. Added load more answers feature 
3. Added css style
4. Confirmed page works fine.
Trello: https://trello.com/c/KygClP4K
@vannguyen-vn @thecaitlinkinney @isabell-lee  Please help review. Thanks!
=> QA - Questions Modal and Load More Answers Feature

client/dist/style.css, client/src/Components/QuestionAnswer/QuestionAnswer.jsx, client/src/Components/QuestionAnswer/QuestionEntryList.jsx
1. Completed Load More Questions Feature
2. Added magnifying glass to search bar and modify minor CSS styles
3. Confirmed website working.
Trello: https://trello.com/c/XleROaug
@vannguyen-vn @thecaitlinkinney @isabell-lee  Please help review. Thanks!
=> QA - Completed Load More Questions Feature

client/dist/style.css, client/src/Components/RatingsAndReviews/AddReviewForm.jsx, client/src/Components/RatingsAndReviews/RatingsAndReviews.jsx, client/src/Components/RatingsAndReviews/ReviewList.jsx, server/rrRoutes.js
@irislavie @vannguyen-vn @isabell-lee 
Hi there - 
Looking to integrate this revised server update into my master code. I pulled from the master before pushing up in hopes of avoiding any merge conflicts. Can you please review?
Trello Ticket: https://trello.com/c/v3pfHCY0
=> Form submits to api

client/dist/style.css, client/src/Components/QuestionAnswer/AddAnswerList.jsx, client/src/Components/QuestionAnswer/AddQuestionList.jsx, client/src/Components/QuestionAnswer/AnswerEntryList.jsx, client/src/Components/QuestionAnswer/AnswerPhotoList.jsx, client/src/Components/QuestionAnswer/QuestionAnswer.jsx, client/src/Components/QuestionAnswer/QuestionCountList.jsx, client/src/Components/QuestionAnswer/QuestionEntryList.jsx, client/src/Components/QuestionAnswer/QuestionReportList.jsx, client/src/app.jsx
Please help review, thanks! @vannguyen-vn @thecaitlinkinney @isabell-lee 
1. Load More Questions: https://trello.com/c/XleROaug
2. Search Feature: https://trello.com/c/kZYq4qyT
3. Image Function: https://trello.com/c/L7eQfEEi
4. Confirmed website working.
=> QA- Load More Question/Search Feature/Image Function

client/dist/style.css, client/src/Components/ProductOverview/POComponents/ImageGallery.jsx
From ticket: https://trello.com/c/8StDPHYj
- Clicking on any thumbnail should update the main image to match that shown in the thumbnail clicked.
- The thumbnail corresponding to the image currently selected as the main image should be highlighted to indicate the current selection.
- Clicking on the currently selected thumbnail will have no further effect.
- Upon clicking the right or left arrow, the main image and the thumbnail highlighted should update.
- Default view is overlaid by the list of thumbnail images. (Still needs formatting) 
Please review
=> PO: Thumbnail feature

client/dist/style.css, client/src/Components/RatingsAndReviews/AddReviewForm.jsx, client/src/Components/RatingsAndReviews/RatingBreakdown.jsx, client/src/Components/RatingsAndReviews/RatingsAndReviews.jsx, client/src/Components/RatingsAndReviews/ReviewList.jsx, client/src/Components/RatingsAndReviews/ReviewTile.jsx, client/src/Components/RatingsAndReviews/SortBar.jsx
@isabell-lee @vannguyen-vn @irislavie 
Can you please review? Mostly updates to CSS for layout and styling. 
Trello: https://trello.com/c/1MzkvBmS
=> Css grid updates

client/dist/style.css, client/src/Components/QuestionAnswer/AddAnswerList.jsx, client/src/Components/QuestionAnswer/AddQuestionList.jsx, client/src/Components/QuestionAnswer/AnswerEntryList.jsx, client/src/Components/QuestionAnswer/QuestionAnswer.jsx, client/src/Components/QuestionAnswer/QuestionEntryList.jsx, server/qaRoutes.js
1. Fixed page refresh bugs for Add Answer and Add Question feature 
2. Added css styles for close button for Add Answer and Add Question modal
3. Confirmed page working
@vannguyen-vn @thecaitlinkinney @isabell-lee  Please help review.
Trello: https://trello.com/c/wscCTTrG
=> QA - Fixed Bugs and Updated CSS Styles

client/dist/style.css, client/src/Components/RatingsAndReviews/RatingBreakdown.jsx, client/src/Components/RatingsAndReviews/RatingsAndReviews.jsx, client/src/Components/RatingsAndReviews/ReviewTile.jsx, client/src/Components/RatingsAndReviews/SortBar.jsx, client/src/app.jsx
@isabell-lee @irislavie @vannguyen-vn 
PR here for styling revisions (it's not gigantic anymore!) on the 
Trello Ticket: https://trello.com/c/1MzkvBmS
=> Revised CSS Layout

client/dist/style.css, client/src/Components/RelatedProducts/ComparisonModal.jsx, client/src/Components/YourOutfitList/YourOutfitCard.jsx, client/src/Components/YourOutfitList/YourOutfitList.jsx, client/src/app.jsx, server/outfitRoutes.js
https://trello.com/c/NHkhYt6n
add a outfit card
fixed browser error by add Tbody
hi guys, pls, review it for me! thanks
=> Outfit list: Add to card

client/src/Components/QuestionAnswer/AnswerEntryList.jsx, client/src/Components/QuestionAnswer/QuestionEntryList.jsx
A minor PR to fix unique key props issue from console and no Trello tickets related.
=> QA - Fix unique key props

client/dist/style.css, client/src/Components/QuestionAnswer/AddAnswerList.jsx
1. Updated feature to allow multiple image upload..but can only support multiple image upload at one select. I added this bug to the log for me to address later.
https://trello.com/c/GTb9yW6B https://trello.com/c/inD6iY6w
=> Updated multiple image upload feature

client/dist/style.css, client/src/Components/ProductOverview/POComponents/AddToCart.jsx, client/src/Components/ProductOverview/POComponents/ImageGallery.jsx, client/src/app.jsx
No associated ticket, just spruced up some things like adding a logo and making some things red to match team zuko
=> Implemented minor styling

client/dist/style.css
=> QA - Search Bar Minor Formatting

client/src/app.jsx
No associated ticket. Wrote this during team meeting. New function updateProductID will update the app's current product ID state dynmaically.
=> Wrote function to update the app's product_id

client/dist/style.css, client/src/Components/RelatedProducts/RelatedProductCard.jsx, client/src/Components/RelatedProducts/RelatedProductsList.jsx, client/src/Components/RelatedProducts/RelatedProductsView.jsx, client/src/app.jsx
https://trello.com/c/cnlKBIFi
when clicking a related Product. It will update the 'product_id' to the detail product page.
hi, Can you take a look, please!
=> Update to the dynamic 'product_id' to the detail product page.

client/src/Components/RatingsAndReviews/AddReviewForm.jsx, client/src/Components/RatingsAndReviews/RatingsAndReviews.jsx, client/src/Components/RatingsAndReviews/ReviewList.jsx, client/src/app.jsx
@isabell-lee @irislavie @vannguyen-vn 
Hi there!
Submitting a PR to cover updates that handle re-rendering R&R widget when related product is clicked. 
Main changes should be in RatingsAndReviews and ReviewList. 
Trello Ticket: https://trello.com/c/DiKbrFco
Thanks!
Caitlin
=> ComponentDidUpdate Update

.gitignore, client/src/Components/YourOutfitList/YourOutfitCard.jsx, client/src/Components/YourOutfitList/YourOutfitList.jsx, client/src/app.jsx, server/outfitRoutes.js
https://trello.com/c/QQ46NROO
Hi guys, can you take a look for me, pls!
=> Add and Delele an outfit

client/dist/style.css, client/src/Components/ProductOverview/POComponents/AddToCart.jsx, client/src/Components/ProductOverview/POComponents/ImageGallery.jsx, client/src/Components/ProductOverview/POComponents/StyleSelector.jsx, client/src/Components/ProductOverview/ProductOverview.jsx, client/src/app.jsx
Began zoom feature:  https://trello.com/c/rBvFMMOy
Tested MouseOver and MouseMove functionality.
Style selector bugs: https://trello.com/c/OEnH0FZf
Have only one checkmark/selected state for a product.
Refactor to depend on style id instead of style name.
No ticket:
Added updateProductName to App for updating product_name state
=> Product overview  updates

client/dist/style.css, client/src/Components/QuestionAnswer/AddAnswerList.jsx, client/src/Components/QuestionAnswer/AnswerEntryList.jsx, server/qaRoutes.js
1. Solved bug on image upload and now support multiple actions on image upload. https://trello.com/c/inD6iY6w
2. Updated feature on bolded word if Answerer is from Seller. https://trello.com/c/L7eQfEEi
=> QA - Image style

.gitignore, client/PhotoAPIConfig.example.js, client/src/Components/RatingsAndReviews/AddReviewForm.jsx, client/src/Components/RatingsAndReviews/RatingsAndReviews.jsx, client/src/Components/RatingsAndReviews/ReviewList.jsx
@isabell-lee @irislavie @vannguyen-vn 
Hi! Can you please review this PR covering the photo upload feature in the review submission form? 
Trello ticket: https://trello.com/c/v3pfHCY0
=> Photo upload

client/src/ClickTracker.jsx, client/src/Components/QuestionAnswer/QuestionEntryList.jsx, server/index.js, server/qaRoutes.js
1. Added ClickTracker.jsx Higher Order Functions
2. Added server routes to post entry to Atelier API Interactions
3. Updated QuestionEntryList to test as an example
@vannguyen-vn @thecaitlinkinney @isabell-lee Please review. Thanks!
https://trello.com/c/XrLrX0qh
=> Change Request Test

client/PhotoAPIConfig.example.js, client/src/Components/QuestionAnswer/AddAnswerList.jsx, client/src/Components/RatingsAndReviews/AddReviewForm.jsx
Updated photo token value in Config.js file. No trello ticket related.
=> Updated photo token in Config.js file

client/src/Components/RelatedProducts/RelatedProductCard.jsx, client/src/Components/YourOutfitList/YourOutfitCard.jsx, client/src/Components/YourOutfitList/YourOutfitList.jsx, server/outfitRoutes.js
https://trello.com/c/Ub8MwuIM
Hi, can you review this for me, pls! thanks
=> Fixed: bug for delete an outfit, featureURL

client/PhotoAPIConfig.example.js, client/src/Components/QuestionAnswer/AnswerEntryList.jsx, client/src/Components/QuestionAnswer/AnswerPhotoList.jsx, server/index.js, server/qaRoutes.js
1. Fixed 'AnswerList.map is not a function' issue by updating server code to remove timeout of 1000ms.
2. Update class to className for a photo icon.
https://trello.com/c/ff88a293
=> QA - Fix issues

client/dist/style.css, client/src/Components/QuestionAnswer/AddAnswerList.jsx, client/src/Components/QuestionAnswer/AddQuestionList.jsx, client/src/Components/QuestionAnswer/QuestionEntryList.jsx
1. Added cursor pointer for clickable sections
2. Added z-index to modal wrapper box 
3. Added rows/columns for textarea for add answer/add question modal box
=> QA - updated CSS styles

client/dist/style.css, client/src/Components/RatingsAndReviews/AddReviewForm.jsx, client/src/Components/RatingsAndReviews/RatingsAndReviews.jsx, client/src/Components/RatingsAndReviews/ReviewList.jsx, client/src/Components/RatingsAndReviews/helpers/ImageModal.jsx
@vannguyen-vn @isabell-lee @irislavie 
Hi! Can you please review this PR covering the following? 
-solves filter bug when a review has been reported but is counted in metadata
-text area default size
-1 pixel border
-pointer cursor
-image modal - 100% width, no height
-object-fit contain on modal box
Trello: https://trello.com/c/vM2ZwCM0
=> CSS updates, filter bug

client/dist/style.css, server/outfitRoutes.js
https://trello.com/c/CMmMopTD
Hi, can you review it for me, pls! thanks
=> Fixed bugs when delete an outfit and update css for popup modal

client/src/Components/ProductOverview/POComponents/AddToCart.jsx, client/src/Components/ProductOverview/POComponents/ImageGallery.jsx, client/src/Components/ProductOverview/POComponents/QuantitySelector.jsx, client/src/Components/ProductOverview/POComponents/SizeSelector.jsx, client/src/app.jsx
https://trello.com/c/cdK0dPcv
- Size Selector: If there is no remaining stock for the current style, the dropdown should become inactive and read “OUT OF STOCK”.
- Add to Cart: If there is no stock: This button should be hidden
Please review.
=> Product overview: style stock

client/dist/style.css, client/src/Components/QuestionAnswer/AnswerCountList.jsx, server/qaRoutes.js
1. Added blur background to Modal pop out
2. Shorten button in See More Answers
=> Qa more css

client/dist/style.css
=> Product overview

client/src/Components/QuestionAnswer/AddAnswerModal.jsx
Fixed bug on closing the whole tab when click outside of modal in the grey background.
=> QA - fixed backdrop close issue

client/dist/style.css, client/src/Components/RatingsAndReviews/RatingBreakdown.jsx, client/src/Components/RatingsAndReviews/RatingsAndReviews.jsx, client/src/Components/RatingsAndReviews/ReviewList.jsx, client/src/Components/RatingsAndReviews/SortBar.jsx, client/src/Components/RatingsAndReviews/helpers/RatingBar.jsx, client/src/Components/RatingsAndReviews/helpers/helpers.js, client/src/app.jsx
@irislavie @vannguyen-vn @isabell-lee 
PR to fix a few bugs/add some details. Main changes should be in ratingsBreakdown.jsx, ratingsBar.jsx, helpers.js, and CSS
Trello: 
Filter selected indicator: https://trello.com/c/SgcRC1oV
% recommended bug: https://trello.com/c/lFiFhI4E
Filter crash: https://trello.com/c/mmJn3VFj
=> Filtering changes

client/dist/index.html, client/src/Components/ProductOverview/POComponents/SocialMediaButtons.jsx
Implemented Facebook, Twitter, and Pinterest share buttons to our website/content.
https://trello.com/c/cdK0dPcv
=> Social media buttons

client/src/Components/RatingsAndReviews/AddReviewForm.jsx, client/src/Components/RatingsAndReviews/RatingsAndReviews.jsx
@irislavie @vannguyen-vn @isabell-lee 
Fixes submission bug so that photo upload is not mandatory for submission 
Can you please review?
Trello: https://trello.com/c/I5nL5dzY
=> Submission bug

client/src/Components/RelatedProducts/RelatedProductCard.jsx, client/src/Components/RelatedProducts/RelatedProductsList.jsx
Fixed bugs: for comparison modal when update the product ID
https://trello.com/c/CMmMopTD
HI, can you take a look for me, Pls! thanks
=> Fixed bugs: for comparision modal when update the product ID

client/dist/style.css
quick update for CSS, please review
=> css update

client/dist/style.css, client/src/Components/QuestionAnswer/AddAnswerList.jsx, client/src/Components/QuestionAnswer/AddQuestionList.jsx, client/src/Components/QuestionAnswer/AnswerCountList.jsx, client/src/Components/QuestionAnswer/AnswerEntryList.jsx, client/src/Components/QuestionAnswer/QuestionCountList.jsx
Reverts hr-rfp55-fec7-zuko/project-catwalk#107
=> Revert "QA- Fixed CSS "

client/dist/style.css
=> Qa css again1

client/dist/style.css, client/src/Components/QuestionAnswer/AddAnswerList.jsx, client/src/Components/QuestionAnswer/AddQuestionList.jsx, client/src/Components/QuestionAnswer/AnswerCountList.jsx
1. Add space in modal form
2. Move see more answers to be align with other parts.
=> Qa css again2

.gitignore, client/dist/index.html, client/src/app.jsx, package-lock.json, package.json, server/index.js, webpack.config.js
Did optimization on liveshare/zoom with group. Please review.
=> Optimization
